# Generated by Django 3.2.25 on 2024-07-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_address_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
