# Generated by Django 3.2.25 on 2024-06-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='otherimages',
            options={'verbose_name_plural': 'Other Images'},
        ),
    ]
