# Generated by Django 3.2.25 on 2024-07-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240626_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_color',
        ),
    ]
